### PR TITLE
Rewrote rpc.Server to get TestClientDo to pass

### PR DESCRIPTION
**Pull request by briancaine**
I believe I got the tests working.

I rewrote `rpc/server.go`. How does it look?

### CODE REVIEW

**Comment by gz-c** [comment]
Probably fine, I wouldn't panic in the Close errors though, just log a warning, theyre not fatal.

**Review by gz-c — CHANGES_REQUESTED** [review]
Don't panic on the close() errors

**Comment by briancaine** [comment]
Done.

**Comment by gz-c** [comment]
It's still failing.

Look at the `Run` and `Shutdown` methods on objects in teller for an example of how to control the lifecycle of an object that performs like this `Server`

**Comment by briancaine** [comment]
There's a race condition between when the server is started, and when the test tries to access it.

I believe the code is otherwise correct.

I added a small (1 second) delay to smooth this out.

**Comment by gz-c** [comment]
OK, will still fail occasionally on travis (it has slow scheduling) but will see

**Review by gz-c — APPROVED** [review]

**Comment by briancaine** [comment]
I was thinking about other ways to solve it. We could set up a channel and close it when we're 100% sure the `http.Server` is up and running. That would work, but I don't think that really has any use in production.

I think a delay is probably our best bet. Maybe if 1 second is too short, we can increase it.

**Pull request merged**
