### PR TITLE
Initialized dep

### PR DESCRIPTION
**Pull request by briancaine**
https://github.com/skycoin/exchange-api/issues/7

So I added the `Gopkg.lock` and `Gopkg.toml` files. Since `dep ensure` populates `vendor`, I thought it might be best if we left that out of git.

### CODE REVIEW

**Comment by gz-c** [comment]
Call `dep prune` after `dep ensure` and commit `vendor/` to the repo

**Comment by briancaine** [comment]
Done.

**Comment by gz-c** [comment]
Need to redo to remove `github.com/pkg/errors`

**Comment by briancaine** [comment]
How's that?

**Pull request merged**
