### PR TITLE
Pass tests

### LINKED ISSUE #29: Fix travis build errors
Errors seen here:

https://travis-ci.org/skycoin/exchange-api/builds/335458623

```
gometalinter --deadline=2m --disable-all -E goimports -E unparam --tests --vendor ./...
cli/c2cx.go:1::warning: file is not goimported (goimports)
cli/create.go:1::warning: file is not goimported (goimports)
cli/render.go:1::warning: file is not goimported (goimports)
rpc/client.go:1::warning: file is not goimported (goimports)
rpc/utils.go:1::warning: file is not goimported (goimports)
exchange/c2cx.com/api.go:28:17:warning: parameter method always receives "getorderbook" (unparam)
```

Need to run `make format` to fix the `goimports` warnings.

`exchange/c2cx.com/api.go:28:17:warning: parameter method always receives "getorderbook"`
This line can be marked with `// nolint: unparam`

### PR DESCRIPTION
**Pull request by briancaine**
Fixes #29

### CODE REVIEW

**Comment by gz-c** [comment]
merge conflicts

**Comment by briancaine** [comment]
https://travis-ci.org/skycoin/exchange-api

The travis log seems to be broken.

Edit: I think I fixed it. Let's see if the tests pass...

**Comment by briancaine** [comment]
Ok, so, the tests passed. However, there's an occasional hiccup with the rpc tests.

```
=== RUN   TestClientDo
2018/02/07 23:29:43 Starting server localhost:12345
2018/02/07 23:29:43 processing request, method balance, params {"currency":"BTC"}
--- PASS: TestClientDo (0.00s)
=== RUN   Test_defaultHandler_GetBalance
2018/02/07 23:29:43 Server stopped
--- PASS: Test_defaultHandler_GetBalance (0.00s)
=== RUN   Test_defaulthandler_Cancel
panic: accept tcp 127.0.0.1:12345: use of closed network connection
```

I think the problem is `TestClientDo` test in `rpc/client_test.go`. It mishandles the network listener and tries to use it after it was closed or something.

If you keep running the tests over and over, they'll pass some of the time.

I'm not sure if we want to disable that test (because it passes sometimes, and when you run that test alone, it passes).

**Comment by gz-c** [comment]
https://github.com/skycoin/exchange-api/issues/35 regarding the flaky test

**Comment by gz-c** [comment]
Also do this one https://github.com/skycoin/exchange-api/issues/36

**Pull request merged**
